Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName : 'accatpics12345678'
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: 'A4L'
      InstanceType: 't2.micro'
      ImageId: 'ami-0a8b4cd432b1c3063'