<CreateDBSubnetGroupResponse xmlns="http://rds.amazonaws.com/doc/2014-09-01/">
    <CreateDBSubnetGroupResult>
        <DBSubnetGroup>
            <VpcId>vpc-002bff77aead4d66f</VpcId>
            <Subnets>
                <Subnet>
                    <SubnetIdentifier>subnet-0714345be5056fcb4</SubnetIdentifier>
                    <SubnetStatus>Active</SubnetStatus>
                    <SubnetAvailabilityZone>
                        <Name>us-east-1a</Name>
                    </SubnetAvailabilityZone>
                </Subnet>
                <Subnet>
                    <SubnetIdentifier>subnet-060b71185a7a6d0a5</SubnetIdentifier>
                    <SubnetStatus>Active</SubnetStatus>
                    <SubnetAvailabilityZone>
                        <Name>us-east-1b</Name>
                    </SubnetAvailabilityZone>
                </Subnet>
            </Subnets>
            <SubnetGroupStatus>Complete</SubnetGroupStatus>
            <DBSubnetGroupDescription>Subnet-3</DBSubnetGroupDescription>
            <DBSubnetGroupName>test-subnetgroup</DBSubnetGroupName>
        </DBSubnetGroup>
    </CreateDBSubnetGroupResult>
    <ResponseMetadata>
        <RequestId>dca7325b-4e18-467a-8817-177337cc258a</RequestId>
    </ResponseMetadata>
</CreateDBSubnetGroupResponse>