import numpy as np
import pandas as pd
#https://www.kaggle.com/code/vaishnavi28krishna/pandas-project/notebook

csv1  = pd.read_csv(r"C:\Users\srini\OneDrive\kaggle\standford_data\police_project.csv")
print(csv1.head())
print(csv1.info())
csv1.drop('county_name',axis=1,inplace=True)
print(csv1.info())
df1 = csv1.copy()
print(df1.head(5))
df1.drop('stop_date',axis=1,inplace=True)
print(df1.head(5))
df1.drop(df1.iloc[[],[0,2,3,4,5,7,8,9,10,11,12]],axis=1,inplace=True)
print(df1.head())
print(df1.driver_gender.value_counts())
print(df1.columns)
print(df1.driver_gender.value_counts(normalize=True))
print(df1.info())
print(df1.violation.value_counts())
print(df1.violation.value_counts(normalize=True))
print(df1[df1.violation=='Speeding'].driver_gender.value_counts())
print(df1[df1.violation=='Speeding'].driver_gender.value_counts(normalize=True))
print(df1[df1.driver_gender=='M'].violation.value_counts())
print(df1[df1.driver_gender =='M'].violation.value_counts(normalize=True))
print(df1[df1.driver_gender =='F'].violation.value_counts())
print(df1[df1.driver_gender =='F'].violation.value_counts(normalize=True))